<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AnalysisModePerformance>All</AnalysisModePerformance>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\App2d.Core\App2d.Core.csproj" />
    <PackageReference Include="SkiaSharp" Version="4.151.1" />
    <Compile Include="..\App2d\Engine\Camera2D.cs" Link="Engine\Camera2D.cs" />
    <Compile Include="..\App2d\Engine\Scene2D.cs" Link="Engine\Scene2D.cs" />
    <Compile Include="..\App2d\Engine\WorldObject2D.cs" Link="Engine\WorldObject2D.cs" />
    <Compile Include="..\App2d\Engine\Rendering\**\*.cs" Link="Engine\Rendering\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
