<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AnalysisModePerformance>All</AnalysisModePerformance>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\App2d.Core\App2d.Core.csproj" />
    <ProjectReference Include="..\App2d.Collision\App2d.Collision.csproj" />
  </ItemGroup>
</Project>
